<?php
/*
 * panel template
 *
 * @package Application
 * @author Vallo Reima
 * @copyright (C)2013
 */
$transit = ¤::Enc(¤::$_->ts, true);
$fnm = ¤::Config('db/nme') . CFG;
$fid = ¤::$_->fid;
$fld = ¤::_('txt.fld');
$cmd = ¤::_('txt.cmd');

function Opts($ops, $flg = false, $def = null)
/*
 * form select options
 * in: ops -- options array
 *     flg -- true - add empty option
 *     def -- default option
 */ {
  if ($flg) {
    $ops[''] = '';
  }
  $htm = '';
  $sld = ' selected="selected"';
  foreach ($ops as $key => $val) {
    $s = $key == $def ? $sld : '';
    $htm .= '<option value="' . $key . '"' . $s . '>' . $val . '</option>' . PHP_EOL;
  }
  return $htm;
}
?>
<form id="<?= $fid; ?>" autocomplete="off">
  <input id="id" type="hidden" value="">
  <table class="modify">
    <tbody>
      <tr class="find">
        <td><label for="fname" id="l_fname"><?php echo $fld['fname']; ?></label></td>
        <td><input id="fname" type="text" maxlength="100"></td>
      </tr>
      <tr class="find">
        <td><label for="lname" id="l_lname"><?php echo $fld['lname']; ?></label></td>
        <td><input id="lname" type="text" maxlength="100"></td>
      </tr>
      <tr>
        <td><label for="birth" id="l_birth"><?php echo $fld['birth']; ?>
            <img src="<?= PICPTH . 'tip.gif' ?>" alt="?" title="<?= ¤::_('txt.tipd'); ?>">
          </label></td>
        <td><input id="birth" type="text" maxlength="10"></td>
      </tr>
      <tr>
        <td><label for="gender" id="l_gender"><?php echo $fld['gender']; ?></label></td>
        <td><select id="gender">
            <?php echo Opts($genders, true, ''); ?>
          </select></td>
      </tr>
      <tr>
        <td><label for="email" id="l_email"><?php echo $fld['email']; ?></label></td>
        <td><input id="email" type="text" maxlength="64"></td>
      </tr>
      <tr>
        <td><label for="address" id="l_address"><?php echo $fld['address']; ?></label></td>
        <td><input id="address" type="text" maxlength="200"></td>
      </tr>
    </tbody>
  </table>
</form>
<div id="browse" class="browse hide">
  <?php include('browse.phtml'); ?>
</div>
<div id="command" class="command hide">
  <button type="button" name="A"><?= $cmd['a']; ?></button>
  <button type="button" name="M"><?= $cmd['m']; ?></button>
  <button type="button" name="D"><?= $cmd['d']; ?></button>
  <button type="button" name="U"><?= $cmd['u']; ?></button>
  <button type="button" name="B"><?= $cmd['b']; ?></button>
  <button type="button" name="R"><?= $cmd['r']; ?></button>
  <button type="button" name="CC"><?= $cmd['cc']; ?></button>
  <button type="button" name="S"><?= $cmd['s']; ?></button>
  <button type="button" name="F"><?= $cmd['f']; ?></button>
  <button type="button" name="O"><?= $cmd['o']; ?></button>
  <button type="button" name="CL"><?= $cmd['cl']; ?></button>
  <button type="button" name="Q"><?= $cmd['q']; ?></button>
</div>
<div id="datepick" class="calendar datepick">
  <table class="change">
    <thead>
      <tr><th colspan="8"><button name="MP" title="<?php echo ¤::_('txt.prm'); ?>">&lt;</button>
          <select name="month">
            <?php echo Opts($months); ?>
          </select>
          <select name="year" id="year">
            <?php echo Opts($years, false, end($years)); ?>
          </select>
          <button name="MN" title="<?php echo ¤::_('txt.ntm'); ?>">&gt;</button>
        </th></tr>
      <tr><?php echo Days($days, ¤::$_->ts['wsuf']); ?></tr>
    </thead>
    <tfoot>
      <tr><th colspan="8"></th></tr>
    </tfoot>
    <tbody>
    </tbody>
  </table>
</div>
<form class="hide" id="transit" target="download" enctype="application/x-www-form-urlencoded" 
      method="post" action="<?= ¤::_('url'); ?>">
  <div><?= $transit; ?></div>
  <input type="hidden" name="srv" value="brw">
  <input type="hidden" name="cmd" value="D">
  <input type="hidden" name="fnm" value="<?= $fnm; ?>">
  <input type="hidden" name="wkf" id="filename">
</form>
<iframe class="hide" name="download"></iframe>
